"""fix errors

Revision ID: 06166b0c7297
Revises: 75696fa6c327
Create Date: 2025-09-14 22:12:55.569103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06166b0c7297'
down_revision = '75696fa6c327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_last_active_date'), ['last_active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_streak_count'), ['streak_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_streak_count'))
        batch_op.drop_index(batch_op.f('ix_user_last_active_date'))

    # ### end Alembic commands ###
