"""Adiciona tabela Measurement

Revision ID: 70349418a4b9
Revises: 3f63ff1573b1
Create Date: 2025-10-25 21:18:21.117641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70349418a4b9'
down_revision = '3f63ff1573b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_user_id'))
        batch_op.drop_index(batch_op.f('ix_measurement_local_id'))

    op.drop_table('measurement')
    # ### end Alembic commands ###
