"""add streak_count and last_active_date to user

Revision ID: 75696fa6c327
Revises: c03cc963e122
Create Date: 2025-09-14 21:22:25.812778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75696fa6c327'
down_revision = 'c03cc963e122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_active_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
